### ISSUE TITLE
How do you configure systemd-boot?

### ISSUE THREAD

**Issue by wirecat** [gtbjj/x205ta#13]
First of all, thank you so much for the guide. I almost have my laptop set up... but I can't get systemd-boot to work for the life of me. Would you mind sharing setup steps for systemd-boot on this laptop? Following the arch wiki didn't seem to result in a bootable system.

Thank you,
Daniel

**Comment by savagezen** [comment]
@wirecat 

Initially I didn't have any problems following [the instructions on the Arch Wiki](https://wiki.archlinux.org/index.php/systemd-boot), but when I tried a fresh install a few months ago that wasn't working.  I don't actively use the machine anymore, so it hasn't been worth it to me to figure out what's going on.

Please feel encouraged to make a pull request if you figure something out.

**Comment by wirecat** [comment]
I've been trying with no success... I may give it a shot again, but I think I'll wait a while. Maybe an update will bring a fix to some bug I'm not aware of and experiencing.
