### ISSUE TITLE
Is it really necessary to have a linux distro to make the iso file?

### ISSUE THREAD

**Issue by SaberAltria** [gtbjj/x205ta#2]
I am sorry that I have no way to contact you, so I put my questions on issue.

I copied the bootia32.efi file downloaded to the iso. 
However, I cannot boot into the proper arch linus installation menu. 
All I got is only the grub command line.

Then, I followed this guide, and ran the following command to manually boot into the arch linux.
https://docs.google.com/document/d/1kbmTJKS37hc4NXBQe9svoBlUmAsITZXnw-3PLIGHDCo/edit#

set root=(hd0,gpt1)
linux   /arch/boot/x86_64/vmlinuz archisobasedir=arch archisolabel=ARCH_201605
initrd  /arch/boot/intel_ucode.img
initrd  /arch/boot/x86_64/archiso

However, it stopped stopped with the error,
"Waiting 30 seconds for device /dev/disk/by-label/"

**Comment by gtbjj** [comment]
No worries about the issue, thanks for your interest!

Yes, you need Linux to alter the iso.  However, you could accomplish the same thing with Virtual Box.  Use a Linux virtual machine to access the USB / iso and remaster it from there.

**Comment by savagezen** [comment]
No worries about the issue, thanks for your interest!

To answer your first question:  ideally you **want** Linux to alter the iso; I'm sure software exists for Windows to alter them though.  However, you could accomplish the same thing with Virtual Box.  Use a Linux virtual machine to access the USB / iso and remaster it from there.

At any rate, there are some errors in your GRUB recovery commands.  I'll open a separate issue and link in another comment.

**Comment by savagezen** [comment]
@SaberAltria , see the correct GRUB prompt commands in [this issue](https://github.com/gtbjj/x205ta/issues/3)
