### ISSUE TITLE
Wi-Fi is not working on Kernel 4.5.4-1 ARCH

### ISSUE THREAD

**Issue by arthurartoria** [gtbjj/x205ta#6]
Any solution to that?

**Comment by savagezen** [comment]
Just booted up and WiFi is working as usual on 4.6.0-1-ARCH when connecting with `wifi-menu`.

As a temporary workaround, if WiFi worked for you prior, you can downgrade the Kernel.

```
$ ls /var/cache/pacman/pkg | grep linux
------
# pacman -U /var/cache/pacman/pkg/linux-4.OLDER.VERSION.pkg.tar.xz
```

You can also look into [manually adding the wireless drivers](https://wiki.archlinux.org/index.php/Asus_x205ta#Adding_wireless_drivers_to_the_install_image).  

I don't remember having any wireless issues for several kernel versions, and those were minor hiccups (for versions after where I noted in the guide).  

---

_Update_:  Just to double check, I downgraded to 4.5.4-1-ARCH, rebooted, and connected with `wifi-menu` just fine.  Could another package upgrade or misconfigured setting be responsible for the breakage?

**Comment by ghost** [comment]
Hi,

wifi-menu doesn't work for me neither from the live iso.

Well to be more explicit, it certainly works, but when there is not exactly
one network interface, you need to provide the chosen interface name.

As I'm really bad at all this network sorcery, I choose to follow what
irfan do in it's tutorial (you can find a link in the installation page of
this repo) and configure a USB connection to an Android device and thus get
an internet connection.

**Comment by savagezen** [comment]
Have you guys tried [enabling WiFi](https://wiki.archlinux.org/index.php/Asus_x205ta#Enable_wifi) after booting a live USB you've made from the [Arch Wiki instructions for this machine](https://wiki.archlinux.org/index.php/Asus_x205ta)?

**Comment by savagezen** [comment]
@pwetosaurus @arthurartoria 

I have compiled, burned, and checked a custom ISO that I remastered to include the 32-bit loader (updated version) as well as the wireless driver(s) for both x86 and i686 architectures.  WiFi was indeed **not working** on the 201606 version of the Arch stock ISO, but the custom one should fix that.  [Download here](https://drive.google.com/file/d/0B2RH_BSaD6YPWlJGV2xlSy1tcVU/view?usp=sharing).

Be sure to format your thumb drive to FAT32 or VFAT and label the volume ARCH_201606.  The [preparation instructions](https://github.com/gtbjj/x205ta/blob/master/README.md) have been updated to include this.

**Comment by ghost** [comment]
____

A really great «thank you», you fix this issue even before I ran into it
(Well, I haven't make a successful install yet, and I thought that the wifi
issue was just a live USB one.

Thanks again !

2016-06-06 6:38 GMT+02:00 Austin notifications@github.com:

**Comment by savagezen** [comment]
I pushed a [new version of the ISO](https://drive.google.com/file/d/0B2RH_BSaD6YPR0dxTU82SnFjMm8/view?usp=sharing) this morning.  Now, not only is the wireless driver patched in, but also the kernel module to enable wifi on boot (e.g. you do not have to [manually enable wifi](https://wiki.archlinux.org/index.php/Asus_x205ta#Enable_wifi) after booting the ISO).  

You should be able to:

1) Boot the ISO

2) Select your architecture

3) run `# wifi-menu` and proceed to install as usual
