### ISSUE TITLE
wifi interface not showing up in ifconfig and netctl

### ISSUE THREAD

**Issue by oblivionb** [gtbjj/x205ta#7]
Hello sir,

I was wondering what went wrong with my install, I picked up your .iso (6 june), mounted it with unetbootin, plugged my key, booted and i got no wireless interface. checked on arch linux wiki but didn't find anything usefull.

Any idea ? 
PS : Any donation link for the big work you've done ?

Best regards.

**Comment by savagezen** [comment]
You will probably get some errors because the wireless driver does not register as wlan0 like it is supposed to.  You should be able to connect to a wireless network with `# wifi-menu`.  After that you can check your connection per usual with `# ping -c 3 www.google.com`.

**Comment by oblivionb** [comment]
After some tries I decided to use a USB-Wireless adaptater (a made in china one at $5) and it works pretty fine now, i'm sure i'll be able to fix the wifi now that i have internet. Thanks for your help mate !
