### ISSUE TITLE
System freeze when suspended by lid close / open

### ISSUE THREAD

**Issue by savagezen** [gtbjj/x205ta#8]
Reported in an [Arch Forum Post](https://bbs.archlinux.org/viewtopic.php?pid=1620359#p1620359):

Using either systemd or pm-suspend to suspend machine when closing lid causes glitching screen and freezing (resulting in need for hard reboot)  after resume.

When using systemd to suspend via keyboard shortcut or command line resumes normally with the appropriate fix applied as described on [Bugs page](https://github.com/gtbjj/x205ta/blob/master/BUGS.md).

**Comment by savagezen** [comment]
A possible workaround is to disable systemd's control over the lid and manually use a keyboard shortcut to run a given suspend / lock command prior to closing the lid.

1) Disable _systemd_'s control over actions-on-lid-close:

```
# nano /etc/systemd/logind.conf
----------------------------------------------
[Login]
#NAutoVTs=6
#ReserveVT=6
#KillUserProcesses=no
#KillOnlyUsers=
#KillExcludeUsers=root
#InhibitDelayMaxSec=5
#HandlePowerKey=poweroff
#HandleSuspendKey=suspend
#HandleHibernateKey=hibernate
HandleLidSwitch=ignore          #suspend
#HandleLidSwitchDocked=ignore
#PowerKeyIgnoreInhibited=no
#SuspendKeyIgnoreInhibited=no
#HibernateKeyIgnoreInhibited=no
#LidSwitchIgnoreInhibited=yes
#HoldoffTimeoutSec=30s
#IdleAction=ignore
#IdleActionSec=30min
#RuntimeDirectorySize=10%
#RemoveIPC=yes
#InhibitorsMax=8192
#SessionsMax=8192
#UserTasksMax=12288
```

2) Restart the service

`# systemctl restart systemd-login`

3)  Configure your DE / WM to map whatever key combination you'd like to:

`systemctl suspend`

**Comment by tallero** [comment]
On Xubuntu 16.10 systemd-login doesn't result as an installed service. Systemctl gives to me:
`# systemctl restart systemd-login`
`Failed to restart systemd-login.service: Unit systemd-login.service not found.`

**Comment by tallero** [comment]
Also, the touchpad and wifi fix script in this page https://github.com/gtbjj/x205ta/blob/master/BUGS.md use `/usr/bin/sh` instead of `/bin/sh`.
Also there `netctl` doesn't figure as a service. You know the equivalent one in *buntu?
Thank you so much for your work.

**Comment by savagezen** [comment]
@tallero

```# systemctl restart systemd-logind```  

I think I made a typo in the guide. I will edit if you confirm.

-----

You can just copy the script and change ```/usr/bin/sh``` to ```/bin/sh``` or whatever shell you'd like to use really.  The preference for ```/usr/bin``` is an Arch thing ([see 2013 news release](https://www.archlinux.org/news/binaries-move-to-usrbin-requiring-update-intervention/)).  I'm not sure how or if that correlates to *buntu.

Use ```# service NetworkManager restart``` for *buntu ([reference](https://ubuntuforums.org/showthread.php?t=2254322&page=32)).  Then, bookmark that thread.  It is the basis for much of my work here.
